
package com.dongzhic.java.ws.aio;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SaveAioService", targetNamespace = "http://ws.source.chis/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface SaveAioService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.source.chis/SaveAioService/executeRequest", output = "http://ws.source.chis/SaveAioService/executeResponse")
    public String execute(
            @WebParam(name = "arg0", partName = "arg0")
                    String arg0);

}
