
package com.dongzhic.java.ws.aio;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SaveAioServiceService", targetNamespace = "http://ws.source.chis/", wsdlLocation = "http://0.0.0.0:12307/chis/SaveAioService?wsdl")
public class SaveAioServiceService
    extends Service
{

    private final static URL SAVEAIOSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException SAVEAIOSERVICESERVICE_EXCEPTION;
    private final static QName SAVEAIOSERVICESERVICE_QNAME = new QName("http://ws.source.chis/", "SaveAioServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://0.0.0.0:12307/chis/SaveAioService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SAVEAIOSERVICESERVICE_WSDL_LOCATION = url;
        SAVEAIOSERVICESERVICE_EXCEPTION = e;
    }

    public SaveAioServiceService() {
        super(__getWsdlLocation(), SAVEAIOSERVICESERVICE_QNAME);
    }

    public SaveAioServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SAVEAIOSERVICESERVICE_QNAME, features);
    }

    public SaveAioServiceService(URL wsdlLocation) {
        super(wsdlLocation, SAVEAIOSERVICESERVICE_QNAME);
    }

    public SaveAioServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SAVEAIOSERVICESERVICE_QNAME, features);
    }

    public SaveAioServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SaveAioServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SaveAioService
     */
    @WebEndpoint(name = "SaveAioServicePort")
    public SaveAioService getSaveAioServicePort() {
        return super.getPort(new QName("http://ws.source.chis/", "SaveAioServicePort"), SaveAioService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SaveAioService
     */
    @WebEndpoint(name = "SaveAioServicePort")
    public SaveAioService getSaveAioServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.source.chis/", "SaveAioServicePort"), SaveAioService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SAVEAIOSERVICESERVICE_EXCEPTION!= null) {
            throw SAVEAIOSERVICESERVICE_EXCEPTION;
        }
        return SAVEAIOSERVICESERVICE_WSDL_LOCATION;
    }

}
